# fly.toml app configuration file generated for tc-user-service on 2025-08-01T11:09:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tc-user-service'
primary_region = 'arn'

[build]

[mount]
  source = 'user_db'
  destination = '/data'
  
[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  private_network = true