services:
  
  nginx:
    build:
      context: backend/nginx
      dockerfile: Dockerfile
    ports:
      - "4433:4433"
      - "8080:8080"
    depends_on:
      - game_service
    container_name: nginx
    volumes:
      - ./backend/nginx/log:/var/log/nginx
      - ./backend/user_service/uploads:/app/uploads:ro
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  game_service:
    build:
      context: ./backend/game_service
      dockerfile: Dockerfile
    container_name: game_service
    volumes:
      - ./backend/game_service/database/data:/app/database/data
      - ./backend/libs:/libs
      - ./backend/game_service/logs:/app/logs
    env_file:
      - ./backend/game_service/.env
    networks:
      - app_network
    restart: unless-stopped

  file_service:
    build:
      context: ./backend/file_service
      dockerfile: Dockerfile
    container_name: file_service
    volumes:
      - ./backend/libs:/libs
      - ./backend/file_service/logs:/app/logs
    networks:
      - app_network
    restart: unless-stopped

  user_service:
    build:
      context: ./backend/user_service
      dockerfile: Dockerfile
    container_name: user_service
    volumes:
      - ./backend/user_service/uploads:/app/uploads
      - ./backend/user_service/database/data:/app/database/data
      - ./backend/libs/error_lib:/app/node_modules/@app/errors
      - ./backend/libs:/libs
      - ./backend/user_service/logs:/app/logs
    env_file:
      - ./backend/user_service/.env
    networks:
      - app_network
    restart: unless-stopped

  googlesignin:
    build:
      context: backend/auth_service
      dockerfile: Dockerfile
    depends_on:
      - game_service
    container_name: GoogleSignIn
    env_file:
      - .env
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  certs:
    driver: local
