### Database Population ###


### Add user1
POST http://localhost:3002/api/register
Content-Type: application/json

{
  "username": "alice42",
  "email": "alice@example.com",
  "password": "Password123",
  "picture": "alice.jpg"
}

### Add user2
POST http://localhost:3002/api/register
Content-Type: application/json

{
  "username": "bob",
  "email": "bob@example.com",
  "password": "Password123",
  "picture": "bob.jpg"
}

### Test G2: Create Game - Multiplayer
POST http://localhost:3001/api/create-game
Content-Type: application/json

{
  "player1Id": 3848,
  "player2Id": 3849
}

### Test G2: Finish Game - Multiplayer
PATCH http://localhost:3001/api/130/finish-game
Content-Type: application/json

{
  "p1score": 3848,
  "p2score": 1,
  "winnerId": 3848
}

### Add Friend Tests ###

### Test 23: Add Friend - Success
POST http://localhost:3002/api/1032/friends
Content-Type: application/json

{
  "friendUsername": "bob"
}

### Delete Friend 
DELETE http://localhost:3002/api/836/delete-friend
Content-Type: application/json

{
  "friendUsername": "bob"
}

### Get user
GET http://localhost:3002/api/3849

### Get user stats

GET http://localhost:3002/api/4320/stats

### Update user stats

PATCH http://localhost:3002/api/4320/update-stats
Content-Type: application/json

{
	"isWinner": false
}


### Get all users
GET http://localhost:3002/api/user-list

### Get friends list

GET http://localhost:3002/api/1032/friends


### Get user games

GET http://localhost:3001/api/user/2962

### Get user match history

GET http://localhost:3002/api/3181/match-history




