worker_processes auto;

events {
    worker_connections 1024;  # Maximum number of simultaneous connections
}

http {

	server_tokens off;
    ignore_invalid_headers on;
    limit_req_zone $binary_remote_addr zone=one:10m rate=25r/s;
	# include /etc/nginx/mime.types;
    default_type application/octet-stream;

	log_format json_combined escape=json '{ "time_local": "$time_local", '
                        '"remote_addr": "$remote_addr", '
                        '"request": "$request", '
                        '"method": "$request_method", '
                        '"status": "$status", '
                        '"body_bytes_sent": "$body_bytes_sent", '
                        '"http_referer": "$http_referer", '
                        '"http_user_agent": "$http_user_agent", '
                        '"request_time": "$request_time" }';

	access_log /var/log/nginx/access.log json_combined;
	error_log /var/log/nginx/error.log debug;
	server {
		listen 8080;
		set $nonce_value $request_id;
		add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
		add_header Content-Security-Policy "default-src 'self'; base-uri 'self'; font-src 'self' https: data:; form-action 'self'; frame-ancestors 'self'; img-src 'self' data:; object-src 'none'; script-src 'self' 'nonce-$nonce_value'; script-src-attr 'none'; style-src 'self' https: 'unsafe-inline'; upgrade-insecure-requests; connect-src 'self' https://tc-user-service.fly.dev https://tc-game-service.fly.dev" always;
		add_header Referrer-Policy "no-referrer-when-cross-origin";
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
		add_header Cross-Origin-Embedder-Policy "require-corp";
		add_header Cross-Origin-Resource-Policy "same-origin";
		add_header Cross-Origin-Opener-Policy "same-origin";
		add_header Permissions-Policy "geolocation=(), camera=(), microphone=(), fullscreen=(self)";

		location / {
			root /frontend/dist;
			index loading.html;
			try_files $uri /loading.html;

			sub_filter NONCE="$nonce_value";
            sub_filter_once on;
            sub_filter_types *;
		}

		location /user {
			proxy_pass https://tc-user-service.fly.dev/api/health;
		}

		location /game {
			proxy_pass https://tc-game-service.fly.dev/api/health;
		}
	}
}