# fly.toml app configuration file generated for tc-game-service on 2025-08-08T10:48:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tc-game-service'
primary_region = 'arn'

[build]

[mount]
  source = 'game_db'
  destination = '/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[experimental]
  private_network = true
