# fly.toml app configuration file generated for pongapp-auth on 2025-07-31T13:10:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pongapp-auth'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[experimental]
  private_network = true
